# Project information
site_name: Agent Development Kit
site_url: https://google.github.io/adk-docs
site_description: >-
  Build powerful multi-agent systems with Agent Development Kit
site_dir: site
exclude_docs:
  api-reference/java/legal/*

# Repository
repo_name: adk-docs
repo_url: https://github.com/google/adk-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright Google 2025&nbsp;&nbsp;|&nbsp;&nbsp;<a href="//policies.google.com/terms">Terms</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="//policies.google.com/privacy">Privacy</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#__consent">Manage cookies</a>

# Validation
validation:
  absolute_links: ignore

# Custom CSS
extra_css:
  - stylesheets/custom.css
  - stylesheets/language-tags.css

# Additional config
extra:
  first_repo_url: https://github.com/google/adk-python
  first_repo_name: adk-python
  first_repo_icon: fontawesome/brands/github
  second_repo_url: https://github.com/google/adk-js
  second_repo_name: adk-js
  second_repo_icon: fontawesome/brands/github
  third_repo_url: https://github.com/google/adk-go
  third_repo_name: adk-go
  third_repo_icon: fontawesome/brands/github
  fourth_repo_url: https://github.com/google/adk-java
  fourth_repo_name: adk-java
  fourth_repo_icon: fontawesome/brands/github
  analytics:
    provider: google
    property: G-DKHZS27PHP
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize repeated visits and preferences,
      as well as to measure the effectiveness of our documentation and
      whether users find the information they need. With your consent,
      you're helping us to make our documentation better.

# Configuration
theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  logo: assets/agent-development-kit.png
  favicon: assets/agent-development-kit.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true


# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        'get-started/local-testing.md': 'runtime/api-server.md'
        'get-started/tutorial.md': 'tutorials/index.md'
        'guides/responsible-agents.md': 'safety/index.md'
        'tools/third-party-tools.md': 'tools/third-party/index.md'
        'tools/third-party/openapi-tools.md': 'tools-custom/openapi-tools.md'
        'tools/openapi-tools.md': 'tools-custom/openapi-tools.md'
        'tutorials/ag-ui.md': 'tools/third-party/ag-ui.md'
        'tools/third-party/langchain.md': 'tools/index.md'
        'tools/third-party/crewai.md': 'tools/index.md'
        'get-started/testing.md': 'runtime/api-server.md'
        'tools/authentication.md': 'tools-custom/authentication.md'
        'tools/function-tools.md': 'tools-custom/function-tools.md'
        'tools/confirmation.md': 'tools-custom/confirmation.md'
        'tools/performance.md': 'tools-custom/performance.md'
        'tools/mcp-tools.md': 'tools-custom/mcp-tools.md'
        'tools/google-cloud/bigquery-agent-analytics.md': 'observability/bigquery-agent-analytics.md'
        'tools/google-cloud-tools.md': 'tools/google-cloud/index.md'
        'tools/built-in-tools.md': 'tools/index.md'
        'sessions/express-mode.md': 'tools/google-cloud/express-mode.md'

  - llmstxt:
      markdown_description: An open-source, code-first toolkit for building, evaluating, and deploying sophisticated AI agents with flexibility and control.
      full_output: llms-full.txt
      sections:
        Build Agents:
        - get-started/*.md
        - tutorials/*.md
        - agents/*.md
        - tools/*.md
        - tools-custom/*.md
        Run Agents:
        - runtime/*.md
        - deploy/*.md
        - observability/*.md
        - evaluation/*.md
        - safety/*.md
        Components:
        - context/*.md
        - sessions/*.md
        - callbacks/*.md
        - artifacts/*.md
        - events/*.md
        - apps/*.md
        - plugins/*.md
        - mcp/*.md
        - a2a/*.md
        - streaming/*.md
        - grounding/*.md
        Reference:
        - api-reference/index.md
        - api-reference/rest/index.md

# Navigation
nav:
  - Home:
    - index.md
  - Build Agents:
    - Get Started:
      - get-started/index.md
      - Python: get-started/python.md
      - TypeScript: get-started/typescript.md
      - Go: get-started/go.md
      - Java: get-started/java.md
    - Build your Agent:
      - tutorials/index.md
      - Multi-tool agent: get-started/quickstart.md
      - Agent team: tutorials/agent-team.md
      - Streaming agent:
        - get-started/streaming/index.md
        - Python: get-started/streaming/quickstart-streaming.md
        - Java: get-started/streaming/quickstart-streaming-java.md
      - Visual Builder: visual-builder/index.md
      - Coding with AI: tutorials/coding-with-ai.md
      - Advanced setup: get-started/installation.md
    - Agents:
      - agents/index.md
      - LLM agents: agents/llm-agents.md
      - Workflow agents:
        - agents/workflow-agents/index.md
        - Sequential agents: agents/workflow-agents/sequential-agents.md
        - Loop agents: agents/workflow-agents/loop-agents.md
        - Parallel agents: agents/workflow-agents/parallel-agents.md
      - Custom agents: agents/custom-agents.md
      - Multi-agent systems: agents/multi-agents.md
      - Agent Config: agents/config.md
    - Models for Agents:
      - agents/models/index.md
      - Gemini: agents/models/google-gemini.md
      - Claude: agents/models/anthropic.md
      - Vertex AI hosted: agents/models/vertex.md
      - Apigee AI Gateway: agents/models/apigee.md
      - Ollama: agents/models/ollama.md
      - vLLM: agents/models/vllm.md
      - LiteLLM: agents/models/litellm.md
    - Tools for Agents:
      - tools/index.md
      - Gemini API tools:
        - tools/gemini-api/index.md
        - Code Execution: tools/gemini-api/code-execution.md
        - Computer use: tools/gemini-api/computer-use.md
        - Google Search: tools/gemini-api/google-search.md
      - Google Cloud tools:
        - tools/google-cloud/index.md
        - Apigee API Hub: tools/google-cloud/apigee-api-hub.md
        - Application Integration: tools/google-cloud/application-integration.md
        - BigQuery: tools/google-cloud/bigquery.md
        - Bigtable: tools/google-cloud/bigtable.md
        - Cloud API Registry: tools/google-cloud/api-registry.md
        - Code Execution with Agent Engine: tools/google-cloud/code-exec-agent-engine.md
        - GKE Code Executor: tools/google-cloud/gke-code-executor.md
        - MCP Toolbox for Databases: tools/google-cloud/mcp-toolbox-for-databases.md
        - RAG Engine: tools/google-cloud/vertex-ai-rag-engine.md
        - Spanner: tools/google-cloud/spanner.md
        - Vertex AI Search: tools/google-cloud/vertex-ai-search.md
        - Vertex AI express mode: tools/google-cloud/express-mode.md
      - Third-party tools:
        - tools/third-party/index.md
        - Atlassian: tools/third-party/atlassian.md
        - ElevenLabs: tools/third-party/elevenlabs.md
        - GitHub: tools/third-party/github.md
        - GitLab: tools/third-party/gitlab.md
        - Hugging Face: tools/third-party/hugging-face.md
        - Linear: tools/third-party/linear.md
        - n8n: tools/third-party/n8n.md
        - Notion: tools/third-party/notion.md
        - PayPal: tools/third-party/paypal.md
        - Qdrant: tools/third-party/qdrant.md
        - Stripe: tools/third-party/stripe.md
        - Agentic UI (AG-UI): tools/third-party/ag-ui.md
      - Tool limitations: tools/limitations.md
    - Custom Tools:
      - tools-custom/index.md
      - Function tools:
        - Overview: tools-custom/function-tools.md
        - Tool performance: tools-custom/performance.md
        - Action confirmations: tools-custom/confirmation.md
      - MCP tools: tools-custom/mcp-tools.md
      - OpenAPI tools: tools-custom/openapi-tools.md
      - Authentication: tools-custom/authentication.md
  - Run Agents:
    - Agent Runtime:
      - Agent Runtime: runtime/index.md
      - Web Interface: runtime/web-interface.md
      - Command Line: runtime/command-line.md
      - API Server: runtime/api-server.md
      - Resume Agents: runtime/resume.md
      - Runtime Config: runtime/runconfig.md
      - Event Loop: runtime/event-loop.md
    - Deployment:
      - deploy/index.md
      - Agent Engine:
        - deploy/agent-engine/index.md
        - Standard deployment: deploy/agent-engine/deploy.md
        - Agent Starter Pack: deploy/agent-engine/asp.md
        - Test deployed agents: deploy/agent-engine/test.md
      - Cloud Run: deploy/cloud-run.md
      - GKE: deploy/gke.md
    - Observability:
      - Logging: observability/logging.md
      - Cloud Trace: observability/cloud-trace.md
      - BigQuery Agent Analytics: observability/bigquery-agent-analytics.md
      - AgentOps: observability/agentops.md
      - Arize AX: observability/arize-ax.md
      - Freeplay: observability/freeplay.md
      - MLflow: observability/mlflow.md
      - Monocle: observability/monocle.md
      - Phoenix: observability/phoenix.md
      - W&B Weave: observability/weave.md
    - Evaluation:
      - evaluate/index.md
      - Criteria: evaluate/criteria.md
      - User Simulation: evaluate/user-sim.md
    - Safety and Security:
      - safety/index.md
  - Components:
    - Technical Overview: get-started/about.md
    - Context:
      - context/index.md
      - Context caching: context/caching.md
      - Context compression: context/compaction.md
    - Sessions & Memory:
      - sessions/index.md
      - Sessions:
        - Overview: sessions/session.md
        - Rewind sessions: sessions/rewind.md
      - State: sessions/state.md
      - Memory: sessions/memory.md
    - Callbacks:
      - callbacks/index.md
      - Types of callbacks: callbacks/types-of-callbacks.md
      - Callback patterns: callbacks/design-patterns-and-best-practices.md
    - Artifacts:
      - artifacts/index.md
    - Events:
      - events/index.md
    - Apps:
      - apps/index.md
    - Plugins:
      - plugins/index.md
      - Reflect and retry: plugins/reflect-and-retry.md
    - MCP:
      - mcp/index.md
    - A2A Protocol:
      - a2a/index.md
      - Introduction to A2A: a2a/intro.md
      - A2A Quickstart (Exposing):
        - Python: a2a/quickstart-exposing.md
        - Go: a2a/quickstart-exposing-go.md
      - A2A Quickstart (Consuming):
        - Python: a2a/quickstart-consuming.md
        - Go: a2a/quickstart-consuming-go.md
    - Bidi-streaming (live):
      - streaming/index.md
      - Bidi-streaming development guide series:
        - Part 1. Intro to streaming: streaming/dev-guide/part1.md
        - Part 2. Sending messages: streaming/dev-guide/part2.md
        - Part 3. Event handling: streaming/dev-guide/part3.md
        - Part 4. Run configuration: streaming/dev-guide/part4.md
        - Part 5. Audio, Images, and Video: streaming/dev-guide/part5.md
      - Streaming Tools: streaming/streaming-tools.md
      - Configuring Bidi-streaming behavior: streaming/configuration.md
    - Grounding:
      - Understanding Google Search Grounding: grounding/google_search_grounding.md
      - Understanding Vertex AI Search Grounding: grounding/vertex_ai_search_grounding.md
  - Reference:
    - Release Notes: release-notes.md
    - API Reference:
      - api-reference/index.md
      - Python ADK: api-reference/python/index.html
      - Typescript ADK: api-reference/typescript/index.html
      - Go ADK: https://pkg.go.dev/google.golang.org/adk" target="_blank
      - Java ADK: api-reference/java/index.html
      - CLI Reference: api-reference/cli/index.html
      - Agent Config Reference: api-reference/agentconfig/index.html
      - REST API: api-reference/rest/index.md
    - Community Resources: community.md
    - Contributing Guide: contributing-guide.md
