name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]
concurrency: preview-${{ github.ref }}
jobs:
  welcome:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Post Preview Instructions
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `ðŸ‘‹ Thanks for your contribution!
            You can enable **PR previews** by adding the \`build-preview\` label to this PR.`
            })
  
  preview:
    runs-on: ubuntu-latest
    if: |
      github.event.action != 'closed' &&
      github.event.action != 'unlabeled' &&
      contains(github.event.pull_request.labels.*.name, 'build-preview')
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Build MkDocs
        run: mkdocs build

      # - name: Inject NoIndex Meta Tag
      #   run: |
      #     find site -name "*.html" -exec sed -i 's/<head>/<head><meta name="robots" content="noindex, nofollow" \/>/g' {} +
        
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site
          repository: Sita04/test-docs-preview
          token: ${{ secrets.PREVIEW_REPO_TOKEN }}
          umbrella-dir: pr-preview
          action: deploy
  cleanup:
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'closed' ||
      (github.event.action == 'unlabeled' && github.event.label.name == 'build-preview')
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site
          repository: Sita04/test-docs-preview
          token: ${{ secrets.PREVIEW_REPO_TOKEN }}
          umbrella-dir: pr-preview
          action: remove
